name: CD - Deploy to VPS

on:
  workflow_run:
    workflows: ["CI - Test"]
    types:
      - completed
    branches:
      - main


jobs:
  build_and_push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker compose build frontend backend
          docker tag travel-manager-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/travel-manager-frontend:latest
          docker tag travel-manager-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/travel-manager-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/travel-manager-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/travel-manager-backend:latest
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd travel-manager

            cat > postgres_db.txt <<EOF
            ${{ secrets.POSTGRES_DB }}
            EOF
            
            cat > postgres_password.txt <<EOF
            ${{ secrets.POSTGRES_PASSWORD }}
            EOF
            
            cat > postgres_user.txt <<EOF
            ${{ secrets.POSTGRES_USER }}
            EOF

            sudo docker compose -f docker-compose.prod.yml pull frontend backend
            sudo docker compose -f docker-compose.prod.yml up -d --build --wait --wait-timeout 1200